<?php
/**
 * TL_ROOT/system/modules/includes/languages/it/modules.php 
 * 
 * Contao extension: includes 0.1.0 stable 
 * Italian translation file 
 * 
 * Copyright : Copyright &copy; 2010 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Paolo Brunelli (PaoloB), http://www.contaocms.it 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FMD']['article']['0'] = "Articolo";
$GLOBALS['TL_LANG']['FMD']['article']['1'] = "Includi un articolo come modulo";
$GLOBALS['TL_LANG']['FMD']['content']['0'] = "Elemento di contenuto";
$GLOBALS['TL_LANG']['FMD']['content']['1'] = "Include un elemento di contenuto come modulo";
 
?>
