<?php
/**
 * TL_ROOT/system/modules/includes/languages/it/tl_module.php 
 * 
 * Contao extension: includes 0.1.0 stable 
 * Italian translation file 
 * 
 * Copyright : Copyright &copy; 2010 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Paolo Brunelli (PaoloB), http://www.contaocms.it 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['cteAlias']['0'] = "Elemento da inserire";
$GLOBALS['TL_LANG']['tl_module']['cteAlias']['1'] = "Selezionare l'elemento che si vuole inserire";
$GLOBALS['TL_LANG']['tl_module']['articleAlias']['0'] = "Articolo da inserire";
$GLOBALS['TL_LANG']['tl_module']['articleAlias']['1'] = "Selezionare l'elemento che si vuole inserire";
$GLOBALS['TL_LANG']['tl_module']['editalias']['0'] = "Modifica l'elemento direttamente";
$GLOBALS['TL_LANG']['tl_module']['editalias']['1'] = "Modifica l'elemento ID %s";
$GLOBALS['TL_LANG']['tl_module']['editarticle']['0'] = "Modifica l'articolo";
$GLOBALS['TL_LANG']['tl_module']['editarticle']['1'] = "Modifica l'articolo ID %s";
 
?>
