<?php
/**
 * TL_ROOT/system/modules/includes/languages/de/modules.php 
 * 
 * Contao extension: includes 0.1.2 stable 
 * Deutsch translation file 
 * 
 * Copyright : Copyright &copy; 2012 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Daniel Kiesel (iCodr8) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FMD']['article']['0'] = "Artikel";
$GLOBALS['TL_LANG']['FMD']['article']['1'] = "Bindet einen Artikel als Modul ein.";
$GLOBALS['TL_LANG']['FMD']['content']['0'] = "Inhaltselement";
$GLOBALS['TL_LANG']['FMD']['content']['1'] = "Bindet ein Inhaltselement als Modul ein.";
 
?>
