<?php
/**
 * TL_ROOT/system/modules/includes/languages/de/tl_module.php 
 * 
 * Contao extension: includes 0.1.2 stable 
 * Deutsch translation file 
 * 
 * Copyright : Copyright &copy; 2012 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Daniel Kiesel (iCodr8) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['cteAlias']['0'] = "Ausgewähltes Inhaltselement";
$GLOBALS['TL_LANG']['tl_module']['cteAlias']['1'] = "Bitte wählen Sie das Inhaltselement aus, das Sie einbinden möchten.";
$GLOBALS['TL_LANG']['tl_module']['articleAlias']['0'] = "Ausgewählter Artikel";
$GLOBALS['TL_LANG']['tl_module']['articleAlias']['1'] = "Bitte wählen Sie den Artikel aus, den Sie einbinden möchten.";
$GLOBALS['TL_LANG']['tl_module']['editalias']['0'] = "Inhaltselement bearbeiten";
$GLOBALS['TL_LANG']['tl_module']['editalias']['1'] = "Inhaltselement ID %s bearbeiten";
$GLOBALS['TL_LANG']['tl_module']['editarticle']['0'] = "Artikel bearbeiten";
$GLOBALS['TL_LANG']['tl_module']['editarticle']['1'] = "Artikel ID %s bearbeiten";
 
?>
