<?php
/**
 * TL_ROOT/system/modules/includes/languages/ru/modules.php 
 * 
 * Contao extension: includes 0.1.0 stable 
 * Russian translation file 
 * 
 * Copyright : Copyright &copy; 2010 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Sergey Dyagovchenko (DyaGa), http://d.sumy.ua/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FMD']['article']['0'] = "Статья";
$GLOBALS['TL_LANG']['FMD']['article']['1'] = "Использовать статью как модуль.";
$GLOBALS['TL_LANG']['FMD']['content']['0'] = "Элемент содержимого";
$GLOBALS['TL_LANG']['FMD']['content']['1'] = "Использовать элемент содержимого как модуль.";
 
?>
