<?php
/**
 * TL_ROOT/system/modules/includes/languages/ru/tl_module.php 
 * 
 * Contao extension: includes 0.1.0 stable 
 * Russian translation file 
 * 
 * Copyright : Copyright &copy; 2010 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Sergey Dyagovchenko (DyaGa), http://d.sumy.ua/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['cteAlias']['0'] = "Используемый элемент";
$GLOBALS['TL_LANG']['tl_module']['cteAlias']['1'] = "Выберите элемент содержимого из списка.";
$GLOBALS['TL_LANG']['tl_module']['articleAlias']['0'] = "Используемая статья";
$GLOBALS['TL_LANG']['tl_module']['articleAlias']['1'] = "Выберите статью из списка.";
$GLOBALS['TL_LANG']['tl_module']['editalias']['0'] = "Редактировать элемент содержимого";
$GLOBALS['TL_LANG']['tl_module']['editalias']['1'] = "Редактировать элемент содержимого ID %s";
$GLOBALS['TL_LANG']['tl_module']['editarticle']['0'] = "Редактировать статью";
$GLOBALS['TL_LANG']['tl_module']['editarticle']['1'] = "Редактировать статью ID %s";
 
?>
